[package]
name = "typelock-derive"
version = "0.5.1"
edition = "2024"
description = "Derive macros for typelock"
readme = "README.md"
repository = "https://github.com/Chuck-ie/typelock"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.23.0"
